# Generated by Django 4.1.6 on 2023-03-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackjackuser',
            name='balance',
            field=models.IntegerField(default=500),
        ),
    ]
