version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=djangoDB
    ports:
      - '5432:5432'
  redis:
    image: redis:5
    ports:
      - '6379:6379'