# Generated by Django 4.1.6 on 2023-02-14 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('pot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('suit', models.IntegerField(max_length=1)),
                ('rank', models.IntegerField(max_length=2)),
                ('img', models.URLField(max_length=100)),
                ('dealt', models.BooleanField(default=False)),
                ('tableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.table')),
                ('userID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
