# Generated by Django 4.1.6 on 2023-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_table_singleplayerid_alter_card_rank_alter_card_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dealer',
            field=models.BooleanField(default=False),
        ),
    ]
