# Generated by Django 4.1.6 on 2023-03-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_card_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='pot',
            field=models.IntegerField(default=0),
        ),
    ]
