# Generated by Django 4.1.6 on 2023-04-13 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_alter_table_pot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='table',
            name='singleplayerID',
        ),
        migrations.AddField(
            model_name='table',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('amount_split', models.IntegerField(default=0)),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.table')),
            ],
        ),
    ]
