# Generated by Django 4.1.6 on 2023-04-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_userid_card_playerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
