# Generated by Django 4.1.6 on 2023-04-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_card_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='split',
            field=models.BooleanField(default=False),
        ),
    ]
