# Generated by Django 4.1.6 on 2023-04-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_playertracker_alter_table_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertracker',
            name='split_status',
            field=models.IntegerField(default=0),
        ),
    ]
