# Generated by Django 4.1.6 on 2023-04-13 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_alter_playertracker_split_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertracker',
            name='tableID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='game.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
