# Generated by Django 4.1.6 on 2023-04-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_playertracker_tableid_alter_table_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertracker',
            name='json_cache',
            field=models.JSONField(null=True),
        ),
    ]
