# Generated by Django 4.1.6 on 2023-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_playertracker_split_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='mp_status',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
